#pragma once

#include "swGUI/Core/System/Events/IEventArgs.h"

#include "swInputLibrary/InputCore/Device.h"


/**@defgroup InputEvents Input Events
@brief Input events generated by events system.

@ingroup Events*/



namespace sw {
namespace gui
{


/**@brief Base class for input events.
@ingroup InputEvents*/
struct InputEventArgs : public IEventArgs
{
	RTTR_ENABLE( IEventArgs )
public:

	input::Device*					Device;			///< Device which produced this event.

public:

	InputEventArgs( input::Device* device )
		: Device( device )
	{}
};

}	// gui
}	// sw
